### ISSUE TITLE
xcombine_vol_data fails for ires=1 for a single process

### ISSUE THREAD

**Issue by specfem3d-zhang-ksu** [geodynamics/specfem3d#398] opened 2015-02-10 16:32 UTC
./bin/xcombine_vol_data 0 0 velocity_Z_it000400 ./OUTPUT_FILES/DATABASES_MPI/ ./OUTPUT_FILES 1
will generate a segmentation fault

**Comment by komatits** [comment] 2015-02-11 01:56
Can you try configuring the code with debugging flags on in file 
flags.guess? this will tell you (and us) where the problem is (you 
should then get a file name and line number in the error message)

Thanks,
Dimitri.

On 02/10/2015 05:32 PM, specfem3d-zhang-ksu wrote:
> ./bin/xcombine_vol_data 0 0 velocity_Z_it000400
> ./OUTPUT_FILES/DATABASES_MPI/ ./OUTPUT_FILES 1
> will generate a segmentation fault
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/issues/398>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by komatits** [comment] 2015-02-12 00:35
PS: to do so (debugging) you will need to configure the code without forced vectorization, i.e.

configure --disable_vectorization
make clean
make all

**Comment by QuLogic** [comment] 2015-02-12 00:44
You can use `./configure --enable-debug` to enable debug flags automatically.

**Comment by komatits** [comment] 2017-07-06 23:05
No news about this for two years, closing it.

**Closed by komatits** 2017-07-06 23:05 UTC
Labels: bug, bug_on_some_machines, in progress, testing
